import { useEffect, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react'

type InquiryForm = { name: string; businessName: string; email: string; phone: string; message: string }
type Theme = 'light' | 'dark'
const nav = [['Work', '#work'], ['Solutions', '#solutions'], ['Process', '#process'], ['Contact', '#contact']] as const
const initialForm: InquiryForm = { name: '', businessName: '', email: '', phone: '', message: '' }
const engine = [['IDEA', 'Find the opportunity worth building.', 'A focused conversation turns a rough thought into a useful direction.'], ['STRATEGY', 'Set the system up for real outcomes.', 'We map users, workflows, priorities and the smallest version that creates value.'], ['DESIGN', 'Make complex work feel simple.', 'Clear interfaces make every next action obvious.'], ['DEVELOPMENT', 'Build a reliable digital core.', 'We turn the plan into fast, dependable software.'], ['AUTOMATION', 'Let the system carry repeatable work.', 'Triggers and workflows keep work moving without constant follow-up.'], ['LAUNCH', 'Put a useful product in real hands.', 'We deploy, learn and improve around the people who use it.']]
const modules = ['Dashboard', 'Customer Management', 'Payments', 'Notifications', 'Analytics', 'Automation']

export default function App() {
  const [theme, setTheme] = useState<Theme>('dark'), [menu, setMenu] = useState(false), [stage, setStage] = useState(0)
  const [business, setBusiness] = useState('Local Business'), [challenge, setChallenge] = useState('Manual work')
  const [form, setForm] = useState(initialForm), [isSubmitting, setIsSubmitting] = useState(false)
  const [submitState, setSubmitState] = useState<{ type: 'idle' | 'success' | 'error'; message: string }>({ type: 'idle', message: '' })
  const [fieldErrors, setFieldErrors] = useState<Record<string, string[]>>({})
  useEffect(() => { const saved = localStorage.getItem('palekar-theme') as Theme | null; setTheme(saved ?? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')) }, [])
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('palekar-theme', theme) }, [theme])
  const whatsapp = () => window.open(`https://wa.me/918928221297?text=${encodeURIComponent("Hi, I'd like to know more about your services")}`, '_blank', 'noopener,noreferrer')
  const change = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => { const { name, value } = event.target; setForm(current => ({ ...current, [name]: value })); setFieldErrors(current => ({ ...current, [name]: [] })) }
  const submit = async (event: FormEvent) => { event.preventDefault(); setIsSubmitting(true); setSubmitState({ type: 'idle', message: '' }); setFieldErrors({}); try { const response = await fetch('/api/inquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) { setSubmitState({ type: 'error', message: result.message ?? 'Please review your details and try again.' }); setFieldErrors(result.errors ?? {}); return }; setSubmitState({ type: 'success', message: result.message ?? 'Thanks! Your inquiry has been received.' }); setForm(initialForm) } catch (error) { console.error(error); setSubmitState({ type: 'error', message: 'Unable to submit the form right now. Please send a WhatsApp message instead.' }) } finally { setIsSubmitting(false) } }
  return <div className="site-shell">
    <header className="site-header"><a href="#top" className="brand"><img src="/logo.png" alt="Palekar Labs logo" /><span><strong>Palekar Labs</strong><small>BUILD. INNOVATE. AUTOMATE.</small></span></a><nav className="desktop-nav">{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="head-actions"><Theme theme={theme} setTheme={setTheme} /><button className="button header-cta" onClick={whatsapp}>Start a conversation <span>↗</span></button><button className="menu-button" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Toggle navigation"><i /><i /></button></div><div className={`mobile-menu ${menu ? 'open' : ''}`}><nav>{nav.map(([label, href], index) => <a key={href} href={href} onClick={() => setMenu(false)}><small>0{index + 1}</small>{label}<b>↗</b></a>)}</nav><div><Theme theme={theme} setTheme={setTheme} /><button className="button" onClick={() => { whatsapp(); setMenu(false) }}>Start a conversation <span>↗</span></button></div></div></header>
    <main id="top"><section className="hero shell"><div className="hero-copy"><p className="eyebrow"><i /> DIGITAL PRODUCT STUDIO / MUMBAI + REMOTE</p><p className="kicker">PALEKAR LABS / DIGITAL SYSTEMS</p><h1>We build digital systems that <em>move businesses forward.</em></h1><p>Strategy, design and engineering for businesses ready to turn friction into a better way of working.</p><div className="button-row"><a className="button" href="#work">Explore our work <span>↗</span></a><a className="button ghost" href="#contact">Start a project <span>→</span></a></div><small className="note">No templates. No guesswork. Software that fits.</small></div><HeroUI /></section><div className="marquee"><span>WEBSITES</span><i>✦</i><span>BUSINESS SYSTEMS</span><i>✦</i><span>AUTOMATION</span><i>✦</i><span>DIGITAL PRODUCTS</span><i>✦</i><span>DASHBOARDS</span></div>
      <section className="section shell" id="solutions"><Intro number="01" label="THE FRICTION" title={<>What’s slowing your <em>business down?</em></>} text="Technology should remove friction, not add another layer of work. Start with the real problem." /><div className="friction-grid">{[['CONVERSATIONS', 'Bring messages, requests and follow-ups into one clear experience.'], ['MANUAL WORK', 'Automate repetitive tasks so your team can focus on meaningful work.'], ['SCATTERED DATA', 'Give important information a dependable, accessible home.'], ['CUSTOMER EXPERIENCE', 'Make your business easier to discover, understand and choose.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><b>↗</b></article>)}</div></section>
      <section className="section experiments" id="work"><div className="shell"><Intro number="02" label="SELECTED EXPERIMENTS" title={<>Concepts that show how <em>good systems feel.</em></>} text="Studio concepts, not client claims. A glimpse of the clear, capable software we love to create." /><div className="experiment-grid"><Experiment kind="command" title="Business Command Center" text="Operations, analytics and automation in one focused place." /><Experiment kind="customer" title="Customer Experience Platform" text="A cleaner way to manage people, requests and communication." /><Experiment kind="automation" title="Automation Engine" text="Turn repetitive business processes into reliable workflows." /></div></div></section>
      <section className="section shell"><Intro number="03" label="DIGITAL COMMAND CENTER" title={<>Your business. <em>One digital command center.</em></>} text="A connected product view of the work that matters: growth, customers, requests and automation." /><CommandCenter /></section>
      <section className="section engine-bg"><div className="shell"><Intro number="04" label="LIVE SYSTEM" title={<>From idea to launch, <em>with momentum.</em></>} text="A thoughtful build process keeps every decision connected to the business outcome." /><div className="engine"><div className="engine-list" role="tablist">{engine.map(([name], index) => <button key={name} onClick={() => setStage(index)} className={stage === index ? 'active' : ''} role="tab" aria-selected={stage === index}><span>0{index + 1}</span>{name}<i /></button>)}</div><div className="engine-detail" role="tabpanel"><p className="eyebrow">0{stage + 1} / ACTIVE STAGE</p><div className="orb"><b>PL</b><i /></div><h3>{engine[stage][1]}</h3><p>{engine[stage][2]}</p><small>PALEKAR LABS / DIGITAL ENGINE</small></div></div></div></section>
      <section className="section shell"><Intro number="05" label="BUILD YOUR SYSTEM" title={<>What could we <em>build for you?</em></>} text="Choose your context and see a first direction for the system behind your next stage of growth." /><div className="config"><div className="controls"><label>01 / BUSINESS<select value={business} onChange={event => setBusiness(event.target.value)}>{['Local Business', 'Restaurant', 'Retail', 'Gym', 'Education', 'Startup', 'Community', 'Other'].map(x => <option key={x}>{x}</option>)}</select></label><label>02 / MAIN CHALLENGE<select value={challenge} onChange={event => setChallenge(event.target.value)}>{['Manual work', 'Customer management', 'Payments', 'Bookings', 'Communication', 'Data management', 'Online presence'].map(x => <option key={x}>{x}</option>)}</select></label></div><div className="builder"><div>YOUR DIGITAL SYSTEM <span>PL / 01</span></div><h3>{business}<br /><em>built to move.</em></h3><p>Designed around <strong>{challenge.toLowerCase()}.</strong></p><section>{modules.map((name, i) => <span key={`${business}${challenge}${name}`} style={{ animationDelay: `${i * 55}ms` }}><i>+</i>{name}</span>)}</section><a href="#contact" className="button">Let’s build it <span>→</span></a></div></div></section>
      <section className="section shell" id="services"><Intro number="06" label="OUTCOMES, NOT OUTPUTS" title={<>What we <em>build.</em></>} /><div className="services">{[['DIGITAL PRESENCE', 'Modern websites that make businesses easier to discover and trust.'], ['BUSINESS SYSTEMS', 'Custom systems designed around real business workflows.'], ['AUTOMATION', 'Reduce repetitive work and streamline operations.'], ['DIGITAL PRODUCTS', 'Turn ideas into usable web applications and products.'], ['DATA & DASHBOARDS', 'Make important business information easier to manage and understand.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><b>↗</b></article>)}</div></section>
      <section className="section why"><div className="shell"><Intro number="07" label="WHY PALEKAR LABS" title={<>Built with more <em>intention.</em></>} /><div className="why-grid">{[['BUILT AROUND YOUR BUSINESS', 'Not generic software.'], ['DESIGNED FOR REAL USERS', 'Simple interfaces people actually understand.'], ['AUTOMATION FIRST', 'Reduce repetitive work wherever possible.'], ['BUILT TO EVOLVE', 'Start with what you need, then expand tomorrow.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="section shell" id="process"><Intro number="08" label="HOW WE WORK" title={<>A clear path from <em>friction to flow.</em></>} /><div className="timeline">{[['DISCOVER', 'Understand the problem.'], ['DESIGN', 'Turn the idea into a clear digital experience.'], ['BUILD', 'Develop the actual system.'], ['LAUNCH', 'Deploy it for real users.'], ['IMPROVE', 'Keep making it better.']].map(([title, text], index) => <article key={title}><span>0{index + 1}</span><i /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="cta shell" id="contact"><div><p className="eyebrow">09 / LET’S MAKE SOMETHING USEFUL</p><h2>Have a problem <em>worth solving?</em></h2><p>Tell us what is slowing work down. We’ll help shape the problem into a digital solution.</p></div><a className="button" href="#contact-form">Start a project <span>↗</span></a></section>
      <section className="contact shell" id="contact-form"><div><p className="eyebrow">START A CONVERSATION</p><h2>Let’s build the thing that makes work <em>easier.</em></h2><nav><button onClick={whatsapp}>WhatsApp <span>↗</span></button><a href="mailto:codebyaryan01@gmail.com">codebyaryan01@gmail.com <span>↗</span></a><a href="https://www.instagram.com/palekarlabs/" target="_blank" rel="noreferrer">Instagram / @palekarlabs <span>↗</span></a></nav></div><form onSubmit={submit}><div className="form-grid"><Field label="Name" name="name" form={form} change={change} error={fieldErrors.name?.[0]} required /><Field label="Business name" name="businessName" form={form} change={change} /><Field label="Email" name="email" type="email" form={form} change={change} error={fieldErrors.email?.[0]} /><Field label="Phone" name="phone" type="tel" form={form} change={change} error={fieldErrors.phone?.[0]} /><label className="wide">What are you trying to improve?<textarea name="message" value={form.message} onChange={change} rows={4} required placeholder="Tell us about the problem, not just the feature." />{fieldErrors.message?.[0] && <small>{fieldErrors.message[0]}</small>}</label></div>{submitState.type !== 'idle' && <div className={`message ${submitState.type}`}>{submitState.message}</div>}<button disabled={isSubmitting} className="button submit">{isSubmitting ? 'Sending...' : 'Send inquiry →'}</button></form></section></main>
    <footer><div className="brand"><img src="/logo.png" alt="Palekar Labs logo" /><span><strong>Palekar Labs</strong><small>BUILD. INNOVATE. AUTOMATE.</small></span></div><nav>{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div><a href="mailto:codebyaryan01@gmail.com">codebyaryan01@gmail.com</a><button onClick={whatsapp}>WhatsApp ↗</button><a href="https://www.instagram.com/palekarlabs/" target="_blank" rel="noreferrer">Instagram</a><p>© Palekar Labs</p></div></footer>
  </div>
}
function Theme({ theme, setTheme }: { theme: Theme; setTheme: (theme: Theme) => void }) { return <button className="theme" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Change color theme">{theme === 'dark' ? '☼' : '◐'}</button> }
function Intro({ number, label, title, text }: { number: string; label: string; title: ReactNode; text?: string }) { return <div className="intro"><p className="eyebrow">{number} / {label}</p><h2>{title}</h2>{text && <p>{text}</p>}</div> }
function HeroUI() { return <div className="hero-ui"><header><span><i /><i /><i /></span> PL / LIVE SYSTEM <b>● ONLINE</b></header><main><div>PRODUCT MOMENTUM <b>+24.8%</b></div><section>{[32,48,43,72,58,88,100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</section><p><span><b>12</b> active workflows</span><span><b>98%</b> system health</span></p></main><aside className="tag-one">+ New signal detected</aside><aside className="tag-two">Automation online <i /></aside></div> }
function Experiment({ kind, title, text }: { kind: string; title: string; text: string }) { return <article className={`experiment ${kind}`}><div className="visual">{kind === 'command' && <>{[35,57,73].map((h, i) => <i key={i} style={{ height: `${h}%` }} />)}<b /></>}{kind === 'customer' && <><i>AM</i><i>RK</i><i>JS</i><b /></>}{kind === 'automation' && <><span>TRIGGER</span><i>→</i><span>ACTION</span><i>→</i><span>DONE</span></>}</div><small>STUDIO CONCEPT</small><h3>{title}</h3><p>{text}</p><b className="arrow">↗</b></article> }
function CommandCenter() { return <div className="command"><header><div><p className="eyebrow">SYSTEM OVERVIEW</p><h3>Good morning, team.</h3></div><span><i /> ALL SYSTEMS LIVE</span></header><div className="metrics">{[['₹4.8L', 'REVENUE THIS MONTH', '+18.4%'], ['1,284', 'ACTIVE CUSTOMERS', '+8.2%'], ['86', 'AUTOMATED TASKS', 'RUNNING'], ['12', 'PENDING REQUESTS', 'REVIEW']].map(([value, label, extra]) => <article key={label}><small>{label}</small><b>{value}</b><em>{extra}</em></article>)}</div><div className="command-body"><section className="chart"><p>GROWTH ACTIVITY <span>LAST 7 DAYS</span></p><svg viewBox="0 0 520 160"><path className="area" d="M0 145 L0 122 L70 109 L135 120 L200 78 L270 97 L340 44 L410 63 L520 12 L520 145 Z" /><path d="M0 122 L70 109 L135 120 L200 78 L270 97 L340 44 L410 63 L520 12" /></svg><small>MON　　 TUE　　 WED　　 THU　　 FRI　　 SAT　　 SUN</small></section><section className="activity"><p>RECENT ACTIVITY <span>VIEW ALL</span></p>{['New request received', 'Payment reminder sent', 'Weekly report is ready'].map((x, i) => <div key={x}><i />{x}<small>{i + 2}m ago</small><b>↗</b></div>)}</section></div><footer><div><i>✦</i><span><b>Automation is working</b><small>14 workflows completed today</small></span></div><p><i /><i /><i /><i /></p><aside>New lead assigned <b>×</b></aside></footer></div> }
function Field({ label, name, type = 'text', form, change, error, required }: { label: string; name: keyof InquiryForm; type?: string; form: InquiryForm; change: (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => void; error?: string; required?: boolean }) { const placeholder = name === 'name' ? 'Your name' : name === 'businessName' ? 'Your business' : name === 'email' ? 'you@example.com' : '+91 ...'; return <label>{label}<input name={name} type={type} value={form[name]} onChange={change} placeholder={placeholder} required={required} />{error && <small>{error}</small>}</label> }
